# Generated by Django 4.2.3 on 2023-07-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_experience_project_tag_alter_tecnology_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_demo',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_github',
            field=models.CharField(max_length=512),
        ),
    ]
