# Generated by Django 4.2.3 on 2023-07-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0005_alter_experience_description_alter_project_url_demo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
