# Generated by Django 4.2.3 on 2023-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='company',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job',
            field=models.CharField(max_length=64),
        ),
    ]
