# Generated by Django 4.2.3 on 2023-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0008_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('previous_url', models.CharField(max_length=64)),
                ('next_url', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
