# Generated by Django 4.2.3 on 2023-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0009_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='next_url',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pages',
            name='previous_url',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
