# Generated by Django 4.2.3 on 2023-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0014_alter_pages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
