# Generated by Django 4.2.3 on 2024-01-07 16:22

import django.core.validators
from django.db import migrations, models
from django.apps import apps
from ..auxiliar import dict_month_to_number

def separate_date(string):
    dates = string.split()
    if len(dates) == 1:
        dates.insert(0, "Enero")
    return [dict_month_to_number.get(dates[0], 1), int(dates[1])]


def convert_dates(model_name):
    Model = apps.get_model("my_portfolio", model_name)
    for model in Model.objects.all():
        model.date_start_month, model.date_start_year = separate_date(model.date_start)
        model.date_end_month, model.date_end_year = separate_date(model.date_end)
        model.save()

def convert_dates_education(apps, schema_editor):
    return convert_dates("Education")

def convert_dates_experience(apps, schema_editor):
    return convert_dates("Experience")


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0016_education_date_end_month_education_date_end_year_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_dates_education),
        migrations.RunPython(convert_dates_experience),
        migrations.RemoveField(
            model_name='education',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date_start',
        ),
        migrations.AlterField(
            model_name='education',
            name='date_end_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_end_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_start_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_start_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_end_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_end_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_start_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_start_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
